// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { GetAvatarsData, GetAvatarsResponses, CreateAvatarData, CreateAvatarResponses, GenerateAvatarData, GenerateAvatarResponses, AvailableAvatarsData, AvailableAvatarsResponses, ForcedStoppedAvatarsData, ForcedStoppedAvatarsResponses, DeleteAvatarData, DeleteAvatarResponses, GetAvatarData, GetAvatarResponses, UpdateAvatarData, UpdateAvatarResponses, WakingUpProbData, WakingUpProbResponses, UpdateAvatarStateData, UpdateAvatarStateResponses, GetAvatarStateData, GetAvatarStateResponses, DeleteAvatarStateData, DeleteAvatarStateResponses, ForceShutdownAvatarData, ForceShutdownAvatarResponses, ForceAwakeAvatarData, ForceAwakeAvatarResponses, CreateActionData, CreateActionResponses, QueryActionsData, QueryActionsResponses, GetActionData, GetActionResponses, GetAvatarActionsData, GetAvatarActionsResponses, GetAvatarActionsTodayData, GetAvatarActionsTodayResponses, GetAvatarPreviousContentActionsActionsAvatarIdPreviousContentGetData, GetAvatarPreviousContentActionsActionsAvatarIdPreviousContentGetResponses, BoomBoomGetData, BoomBoomGetResponses } from './types.gen';
import { zGetAvatarsData, zGetAvatarsResponse, zCreateAvatarData, zCreateAvatarResponse, zGenerateAvatarData, zGenerateAvatarResponse, zAvailableAvatarsData, zAvailableAvatarsResponse, zForcedStoppedAvatarsData, zForcedStoppedAvatarsResponse, zDeleteAvatarData, zDeleteAvatarResponse, zGetAvatarData, zGetAvatarResponse, zUpdateAvatarData, zUpdateAvatarResponse, zWakingUpProbData, zWakingUpProbResponse, zUpdateAvatarStateData, zUpdateAvatarStateResponse, zGetAvatarStateData, zGetAvatarStateResponse, zDeleteAvatarStateData, zDeleteAvatarStateResponse, zForceShutdownAvatarData, zForceShutdownAvatarResponse, zForceAwakeAvatarData, zForceAwakeAvatarResponse, zCreateActionData, zCreateActionResponse, zQueryActionsData, zQueryActionsResponse, zGetActionData, zGetActionResponse, zGetAvatarActionsData, zGetAvatarActionsResponse, zGetAvatarActionsTodayData, zGetAvatarActionsTodayResponse, zGetAvatarPreviousContentActionsActionsAvatarIdPreviousContentGetData, zGetAvatarPreviousContentActionsActionsAvatarIdPreviousContentGetResponse, zBoomBoomGetData } from './zod.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List Avatars
 */
export const getAvatars = <ThrowOnError extends boolean = false>(options?: Options<GetAvatarsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetAvatarsResponses, unknown, ThrowOnError>({
        requestValidator: async (data) => {
            return await zGetAvatarsData.parseAsync(data);
        },
        responseValidator: async (data) => {
            return await zGetAvatarsResponse.parseAsync(data);
        },
        security: [
            {
                name: 'X-API-Key',
                type: 'apiKey'
            }
        ],
        url: '/avatars/',
        ...options
    });
};

/**
 * Create Avatar
 */
export const createAvatar = <ThrowOnError extends boolean = false>(options: Options<CreateAvatarData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateAvatarResponses, unknown, ThrowOnError>({
        requestValidator: async (data) => {
            return await zCreateAvatarData.parseAsync(data);
        },
        responseValidator: async (data) => {
            return await zCreateAvatarResponse.parseAsync(data);
        },
        security: [
            {
                name: 'X-API-Key',
                type: 'apiKey'
            }
        ],
        url: '/avatars/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Generate Avatar
 */
export const generateAvatar = <ThrowOnError extends boolean = false>(options: Options<GenerateAvatarData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<GenerateAvatarResponses, unknown, ThrowOnError>({
        requestValidator: async (data) => {
            return await zGenerateAvatarData.parseAsync(data);
        },
        responseValidator: async (data) => {
            return await zGenerateAvatarResponse.parseAsync(data);
        },
        security: [
            {
                name: 'X-API-Key',
                type: 'apiKey'
            }
        ],
        url: '/avatars/generate',
        ...options
    });
};

/**
 * Get Available Avatars
 */
export const availableAvatars = <ThrowOnError extends boolean = false>(options?: Options<AvailableAvatarsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<AvailableAvatarsResponses, unknown, ThrowOnError>({
        requestValidator: async (data) => {
            return await zAvailableAvatarsData.parseAsync(data);
        },
        responseValidator: async (data) => {
            return await zAvailableAvatarsResponse.parseAsync(data);
        },
        security: [
            {
                name: 'X-API-Key',
                type: 'apiKey'
            }
        ],
        url: '/avatars/available_avatars',
        ...options
    });
};

/**
 * Get Forced Stopped Avatars
 */
export const forcedStoppedAvatars = <ThrowOnError extends boolean = false>(options?: Options<ForcedStoppedAvatarsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<ForcedStoppedAvatarsResponses, unknown, ThrowOnError>({
        requestValidator: async (data) => {
            return await zForcedStoppedAvatarsData.parseAsync(data);
        },
        responseValidator: async (data) => {
            return await zForcedStoppedAvatarsResponse.parseAsync(data);
        },
        security: [
            {
                name: 'X-API-Key',
                type: 'apiKey'
            }
        ],
        url: '/avatars/forced_stopped_avatars',
        ...options
    });
};

/**
 * Delete Avatar
 */
export const deleteAvatar = <ThrowOnError extends boolean = false>(options: Options<DeleteAvatarData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeleteAvatarResponses, unknown, ThrowOnError>({
        requestValidator: async (data) => {
            return await zDeleteAvatarData.parseAsync(data);
        },
        responseValidator: async (data) => {
            return await zDeleteAvatarResponse.parseAsync(data);
        },
        security: [
            {
                name: 'X-API-Key',
                type: 'apiKey'
            }
        ],
        url: '/avatars/{avatar_id}',
        ...options
    });
};

/**
 * Get Avatar
 */
export const getAvatar = <ThrowOnError extends boolean = false>(options: Options<GetAvatarData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetAvatarResponses, unknown, ThrowOnError>({
        requestValidator: async (data) => {
            return await zGetAvatarData.parseAsync(data);
        },
        responseValidator: async (data) => {
            return await zGetAvatarResponse.parseAsync(data);
        },
        security: [
            {
                name: 'X-API-Key',
                type: 'apiKey'
            }
        ],
        url: '/avatars/{avatar_id}',
        ...options
    });
};

/**
 * Update Avatar
 */
export const updateAvatar = <ThrowOnError extends boolean = false>(options: Options<UpdateAvatarData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<UpdateAvatarResponses, unknown, ThrowOnError>({
        requestValidator: async (data) => {
            return await zUpdateAvatarData.parseAsync(data);
        },
        responseValidator: async (data) => {
            return await zUpdateAvatarResponse.parseAsync(data);
        },
        security: [
            {
                name: 'X-API-Key',
                type: 'apiKey'
            }
        ],
        url: '/avatars/{avatar_id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Waking Up Probability
 */
export const wakingUpProb = <ThrowOnError extends boolean = false>(options: Options<WakingUpProbData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<WakingUpProbResponses, unknown, ThrowOnError>({
        requestValidator: async (data) => {
            return await zWakingUpProbData.parseAsync(data);
        },
        responseValidator: async (data) => {
            return await zWakingUpProbResponse.parseAsync(data);
        },
        security: [
            {
                name: 'X-API-Key',
                type: 'apiKey'
            }
        ],
        url: '/avatars/waking_up_probability/{avatar_id}',
        ...options
    });
};

/**
 * Update Avatar State
 */
export const updateAvatarState = <ThrowOnError extends boolean = false>(options: Options<UpdateAvatarStateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<UpdateAvatarStateResponses, unknown, ThrowOnError>({
        requestValidator: async (data) => {
            return await zUpdateAvatarStateData.parseAsync(data);
        },
        responseValidator: async (data) => {
            return await zUpdateAvatarStateResponse.parseAsync(data);
        },
        security: [
            {
                name: 'X-API-Key',
                type: 'apiKey'
            }
        ],
        url: '/avatars/state/{avatar_id}/{state}',
        ...options
    });
};

/**
 * Get Avatar State
 */
export const getAvatarState = <ThrowOnError extends boolean = false>(options: Options<GetAvatarStateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetAvatarStateResponses, unknown, ThrowOnError>({
        requestValidator: async (data) => {
            return await zGetAvatarStateData.parseAsync(data);
        },
        responseValidator: async (data) => {
            return await zGetAvatarStateResponse.parseAsync(data);
        },
        security: [
            {
                name: 'X-API-Key',
                type: 'apiKey'
            }
        ],
        url: '/avatars/state/{avatar_id}',
        ...options
    });
};

/**
 * Delete Avatar State
 */
export const deleteAvatarState = <ThrowOnError extends boolean = false>(options: Options<DeleteAvatarStateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeleteAvatarStateResponses, unknown, ThrowOnError>({
        requestValidator: async (data) => {
            return await zDeleteAvatarStateData.parseAsync(data);
        },
        responseValidator: async (data) => {
            return await zDeleteAvatarStateResponse.parseAsync(data);
        },
        security: [
            {
                name: 'X-API-Key',
                type: 'apiKey'
            }
        ],
        url: '/avatars/state/{state_id}',
        ...options
    });
};

/**
 * Force Shutdown Avatar
 */
export const forceShutdownAvatar = <ThrowOnError extends boolean = false>(options: Options<ForceShutdownAvatarData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<ForceShutdownAvatarResponses, unknown, ThrowOnError>({
        requestValidator: async (data) => {
            return await zForceShutdownAvatarData.parseAsync(data);
        },
        responseValidator: async (data) => {
            return await zForceShutdownAvatarResponse.parseAsync(data);
        },
        security: [
            {
                name: 'X-API-Key',
                type: 'apiKey'
            }
        ],
        url: '/avatars/force_shutdown/{avatar_id}',
        ...options
    });
};

/**
 * Force Awake Avatar
 */
export const forceAwakeAvatar = <ThrowOnError extends boolean = false>(options: Options<ForceAwakeAvatarData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<ForceAwakeAvatarResponses, unknown, ThrowOnError>({
        requestValidator: async (data) => {
            return await zForceAwakeAvatarData.parseAsync(data);
        },
        responseValidator: async (data) => {
            return await zForceAwakeAvatarResponse.parseAsync(data);
        },
        security: [
            {
                name: 'X-API-Key',
                type: 'apiKey'
            }
        ],
        url: '/avatars/force_awake/{avatar_id}',
        ...options
    });
};

/**
 * Create Action
 */
export const createAction = <ThrowOnError extends boolean = false>(options: Options<CreateActionData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateActionResponses, unknown, ThrowOnError>({
        requestValidator: async (data) => {
            return await zCreateActionData.parseAsync(data);
        },
        responseValidator: async (data) => {
            return await zCreateActionResponse.parseAsync(data);
        },
        security: [
            {
                name: 'X-API-Key',
                type: 'apiKey'
            }
        ],
        url: '/actions/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Query Actions
 */
export const queryActions = <ThrowOnError extends boolean = false>(options: Options<QueryActionsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<QueryActionsResponses, unknown, ThrowOnError>({
        requestValidator: async (data) => {
            return await zQueryActionsData.parseAsync(data);
        },
        responseValidator: async (data) => {
            return await zQueryActionsResponse.parseAsync(data);
        },
        security: [
            {
                name: 'X-API-Key',
                type: 'apiKey'
            }
        ],
        url: '/actions/query_actions/{avatar_id}',
        ...options
    });
};

/**
 * Get Action
 */
export const getAction = <ThrowOnError extends boolean = false>(options: Options<GetActionData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetActionResponses, unknown, ThrowOnError>({
        requestValidator: async (data) => {
            return await zGetActionData.parseAsync(data);
        },
        responseValidator: async (data) => {
            return await zGetActionResponse.parseAsync(data);
        },
        security: [
            {
                name: 'X-API-Key',
                type: 'apiKey'
            }
        ],
        url: '/actions/{action_id}',
        ...options
    });
};

/**
 * Get Avatar Actions
 */
export const getAvatarActions = <ThrowOnError extends boolean = false>(options: Options<GetAvatarActionsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetAvatarActionsResponses, unknown, ThrowOnError>({
        requestValidator: async (data) => {
            return await zGetAvatarActionsData.parseAsync(data);
        },
        responseValidator: async (data) => {
            return await zGetAvatarActionsResponse.parseAsync(data);
        },
        security: [
            {
                name: 'X-API-Key',
                type: 'apiKey'
            }
        ],
        url: '/actions/avatar/{avatar_id}',
        ...options
    });
};

/**
 * Get Avatar Actions Today
 */
export const getAvatarActionsToday = <ThrowOnError extends boolean = false>(options: Options<GetAvatarActionsTodayData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetAvatarActionsTodayResponses, unknown, ThrowOnError>({
        requestValidator: async (data) => {
            return await zGetAvatarActionsTodayData.parseAsync(data);
        },
        responseValidator: async (data) => {
            return await zGetAvatarActionsTodayResponse.parseAsync(data);
        },
        security: [
            {
                name: 'X-API-Key',
                type: 'apiKey'
            }
        ],
        url: '/actions/avatar/{avatar_id}/today',
        ...options
    });
};

/**
 * Get Avatar Previous Content
 */
export const getAvatarPreviousContentActionsActionsAvatarIdPreviousContentGet = <ThrowOnError extends boolean = false>(options: Options<GetAvatarPreviousContentActionsActionsAvatarIdPreviousContentGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetAvatarPreviousContentActionsActionsAvatarIdPreviousContentGetResponses, unknown, ThrowOnError>({
        requestValidator: async (data) => {
            return await zGetAvatarPreviousContentActionsActionsAvatarIdPreviousContentGetData.parseAsync(data);
        },
        responseValidator: async (data) => {
            return await zGetAvatarPreviousContentActionsActionsAvatarIdPreviousContentGetResponse.parseAsync(data);
        },
        security: [
            {
                name: 'X-API-Key',
                type: 'apiKey'
            }
        ],
        url: '/actions/actions/{avatar_id}/previous_content',
        ...options
    });
};

/**
 * Boom
 */
export const boomBoomGet = <ThrowOnError extends boolean = false>(options?: Options<BoomBoomGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<BoomBoomGetResponses, unknown, ThrowOnError>({
        requestValidator: async (data) => {
            return await zBoomBoomGetData.parseAsync(data);
        },
        url: '/boom',
        ...options
    });
};