// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

/**
 * Type
 */
export const zType = z.enum([
    'send_message',
    'send_bulk_messages',
    'join_group',
    'leave_group',
    'reply_to_message',
    'forward_message',
    'behavioural',
    'read_messages',
    'resolve_phone',
    'interact_with_tweet',
    'scroll_feed',
    'close_browser',
    'publish_post',
    'ask_grok',
    'get_notifications',
    'get_tweet_engagment',
    'change_following_state'
]);

/**
 * Platform
 */
export const zPlatform = z.enum([
    'telegram',
    'twitter'
]);

/**
 * ScrollFeedArgs
 */
export const zScrollFeedArgs = z.object({
    url: z.union([
        z.string(),
        z.null()
    ]).optional(),
    scroll_count: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    wait_time_after_scroll_in_seconds: z.union([
        z.number().int(),
        z.null()
    ]).optional()
});

/**
 * ChatType
 */
export const zChatType = z.enum([
    'User',
    'Group',
    'Channel',
    'Bot',
    'Unknown'
]);

/**
 * ChatInfo
 */
export const zChatInfo = z.object({
    id: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    name: z.union([
        z.string(),
        z.null()
    ]).optional(),
    phone_number: z.union([
        z.string(),
        z.null()
    ]).optional(),
    title: z.union([
        z.string(),
        z.null()
    ]).optional(),
    type: z.union([
        zChatType,
        z.null()
    ]).optional(),
    description: z.union([
        z.string(),
        z.null()
    ]).optional(),
    read_inbox_max_id: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    read_outbox_max_id: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    unread_count: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    unread_mentions_count: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    unread_reactions_count: z.union([
        z.number().int(),
        z.null()
    ]).optional()
});

/**
 * Attachment
 */
export const zAttachment = z.object({
    url: z.string(),
    s3_uri: z.union([
        z.string(),
        z.null()
    ]).optional(),
    name: z.union([
        z.string(),
        z.null()
    ]).optional(),
    mime_type: z.union([
        z.string(),
        z.null()
    ]).optional()
});

/**
 * InputMessage
 */
export const zInputMessage = z.object({
    text: z.union([
        z.string(),
        z.null()
    ]).optional(),
    attachments: z.union([
        z.array(zAttachment),
        z.null()
    ]).optional()
});

/**
 * SendMessageArgs
 */
export const zSendMessageArgs = z.object({
    chat: zChatInfo,
    input_message_content: zInputMessage
});

/**
 * SendBulkMessagesArgs
 */
export const zSendBulkMessagesArgs = z.object({
    chat: zChatInfo,
    messages: z.array(z.string()),
    interval: z.union([
        z.number(),
        z.null()
    ]).optional()
});

/**
 * JoinGroupArgs
 */
export const zJoinGroupArgs = z.object({
    chat: z.union([
        zChatInfo,
        z.null()
    ]).optional(),
    join_discussion_group_if_availble: z.union([
        z.boolean(),
        z.null()
    ]).optional(),
    invite_link: z.union([
        z.string(),
        z.null()
    ]).optional()
});

/**
 * LeaveGroupArgs
 */
export const zLeaveGroupArgs = z.object({
    chat: zChatInfo
});

/**
 * MessageInfo
 */
export const zMessageInfo = z.object({
    timestamp: z.string(),
    peer_id: z.union([
        z.string(),
        z.null()
    ]).optional(),
    from_id: z.union([
        z.string(),
        z.null()
    ]).optional(),
    text_hash: z.union([
        z.string(),
        z.null()
    ]).optional(),
    message_id: z.union([
        z.string(),
        z.null()
    ]).optional(),
    viewer_id: z.union([
        z.string(),
        z.null()
    ]).optional()
});

/**
 * ReplyToMessageArgs
 */
export const zReplyToMessageArgs = z.object({
    chat: z.union([
        zChatInfo,
        z.null()
    ]).optional(),
    message_info: z.union([
        zMessageInfo,
        z.null()
    ]).optional(),
    input_message_content: zInputMessage,
    message_link: z.union([
        z.string(),
        z.null()
    ]).optional()
});

/**
 * ForwardMessageArgs
 */
export const zForwardMessageArgs = z.object({
    from_chat: z.union([
        zChatInfo,
        z.null()
    ]).optional(),
    message_info: z.union([
        zMessageInfo,
        z.null()
    ]).optional(),
    target_chat: zChatInfo,
    message: z.union([
        zInputMessage,
        z.null()
    ]).optional(),
    message_link: z.union([
        z.string(),
        z.null()
    ]).optional()
});

/**
 * SyncPersonalDetailsArgs
 */
export const zSyncPersonalDetailsArgs = z.object({
    first_name: z.union([
        z.string(),
        z.null()
    ]).optional(),
    last_name: z.union([
        z.string(),
        z.null()
    ]).optional(),
    bio: z.union([
        z.string(),
        z.null()
    ]).optional(),
    username: z.union([
        z.string(),
        z.null()
    ]).optional()
});

/**
 * BehaviouralArgs
 */
export const zBehaviouralArgs = z.object({
    wait_time: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    sync_context: z.union([
        z.boolean(),
        z.null()
    ]).optional(),
    get_chats: z.union([
        z.boolean(),
        z.null()
    ]).optional(),
    sync_personal_details: z.union([
        zSyncPersonalDetailsArgs,
        z.null()
    ]).optional(),
    disable_auto_download_media: z.union([
        z.boolean(),
        z.null()
    ]).optional(),
    delete_all_active_sessions: z.union([
        z.boolean(),
        z.null()
    ]).optional(),
    get_unread_messages: z.union([
        z.boolean(),
        z.null()
    ]).optional()
});

/**
 * ReadMessagesArgs
 */
export const zReadMessagesArgs = z.object({
    chat: zChatInfo,
    amount_messages: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    read_all_in_end: z.union([
        z.boolean(),
        z.null()
    ]).optional()
});

/**
 * ResolvePhoneArgs
 */
export const zResolvePhoneArgs = z.object({
    phone_number: z.string()
});

/**
 * TweetContent
 */
export const zTweetContent = z.object({
    text: z.string(),
    media: z.union([
        z.array(z.string()),
        z.null()
    ]).optional()
});

/**
 * TweetInteraction
 */
export const zTweetInteraction = z.object({
    like: z.union([
        z.boolean(),
        z.null()
    ]).optional(),
    retweet: z.union([
        z.boolean(),
        z.null()
    ]).optional(),
    bookmark: z.union([
        z.boolean(),
        z.null()
    ]).optional(),
    reply: z.union([
        zTweetContent,
        z.null()
    ]).optional(),
    quote: z.union([
        zTweetContent,
        z.null()
    ]).optional()
});

/**
 * InteractWithTweetArgs
 */
export const zInteractWithTweetArgs = z.object({
    url: z.string(),
    interaction: zTweetInteraction
});

/**
 * InteractWithTweetByTweetIdArgs
 */
export const zInteractWithTweetByTweetIdArgs = z.object({
    tweet_id: z.number().int(),
    interaction: zTweetInteraction
});

/**
 * CloseBrowserArgs
 */
export const zCloseBrowserArgs = z.object({});

/**
 * ActionStatusCode
 */
export const zActionStatusCode = z.enum([
    'success',
    'failed',
    'cancelled',
    'fail_fast',
    'running',
    'pending'
]);

/**
 * ActionErrorCode
 */
export const zActionErrorCode = z.enum([
    'chat_not_found',
    'general_error',
    'account_muted',
    'send_message_error',
    'message_deleted',
    'sending_attachment_error',
    'did_not_find_message_after_sending',
    'username_not_valid',
    'failed_to_download_attachment',
    'join_group_chat_type_user',
    'account_in_slow_mode',
    'timeout',
    'tweet_does_not_exist',
    'tweet_is_unavailable',
    'tweet_page_load_failed'
]);

/**
 * ActionStatus
 */
export const zActionStatus = z.object({
    status_code: zActionStatusCode,
    error: z.union([
        z.string(),
        z.null()
    ]).optional(),
    error_code: z.union([
        zActionErrorCode,
        z.null()
    ]).optional()
});

/**
 * Url
 */
export const zUrl: z.AnyZodObject = z.object({
    indices: z.array(z.number().int()),
    link: z.string(),
    text: z.string()
});

/**
 * Hashtag
 */
export const zHashtag: z.AnyZodObject = z.object({
    indices: z.array(z.number().int()),
    text: z.string()
});

/**
 * Cashtag
 */
export const zCashtag: z.AnyZodObject = z.object({
    indices: z.array(z.number().int()),
    text: z.string()
});

/**
 * Mention
 */
export const zMention: z.AnyZodObject = z.object({
    indices: z.array(z.number().int()),
    text: z.string()
});

/**
 * Entities
 */
export const zEntities: z.AnyZodObject = z.object({
    urls: z.union([
        z.array(zUrl),
        z.null()
    ]).optional(),
    hashtags: z.union([
        z.array(zHashtag),
        z.null()
    ]).optional(),
    cashtags: z.union([
        z.array(zCashtag),
        z.null()
    ]).optional(),
    mentions: z.union([
        z.array(zMention),
        z.null()
    ]).optional()
});

/**
 * PublicMetrics
 */
export const zPublicMetrics: z.AnyZodObject = z.object({
    retweet_count: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    reply_count: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    like_count: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    quote_count: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    bookmark_count: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    impression_count: z.union([
        z.number().int(),
        z.null()
    ]).optional()
});

/**
 * Tweet
 */
export const zTweet: z.AnyZodObject = z.object({
    tweet_id: z.number().int(),
    author_id: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    author_name: z.union([
        z.string(),
        z.null()
    ]).optional(),
    author_username: z.union([
        z.string(),
        z.null()
    ]).optional(),
    creation_date: z.union([
        z.string(),
        z.null()
    ]).optional(),
    media_attachments: z.union([
        z.array(zAttachment),
        z.null()
    ]).optional(),
    inner_tweet: z.union([
        z.lazy(() => {
            return zTweet;
        }),
        z.null()
    ]).optional(),
    text: z.string(),
    entities: z.union([
        zEntities,
        z.null()
    ]).optional(),
    public_metrics: z.union([
        zPublicMetrics,
        z.null()
    ]).optional(),
    geo: z.union([
        z.object({}),
        z.null()
    ]).optional(),
    in_reply_to_status_id: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    in_reply_to_user_id: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    quoted_status_id: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    is_quote_status: z.union([
        z.boolean(),
        z.null()
    ]).optional(),
    retweeted: z.union([
        z.boolean(),
        z.null()
    ]).optional(),
    possibly_sensitive: z.union([
        z.boolean(),
        z.null()
    ]).optional(),
    lang: z.union([
        z.string(),
        z.null()
    ]).optional(),
    referenced_tweets: z.union([
        z.array(z.object({})),
        z.null()
    ]).optional(),
    public_metrics_samples: z.union([
        z.array(zPublicMetrics),
        z.null()
    ]).optional()
});

/**
 * ScrollFeedResponseContent
 */
export const zScrollFeedResponseContent: z.AnyZodObject = z.object({
    tweets_collected: z.array(zTweet)
});

/**
 * TweetInteractionResult
 */
export const zTweetInteractionResult: z.AnyZodObject = z.object({
    like: z.union([
        zActionStatus,
        z.null()
    ]).optional(),
    retweet: z.union([
        zActionStatus,
        z.null()
    ]).optional(),
    bookmark: z.union([
        zActionStatus,
        z.null()
    ]).optional(),
    reply: z.union([
        zActionStatus,
        z.null()
    ]).optional(),
    reply_tweet_id: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    quote: z.union([
        zActionStatus,
        z.null()
    ]).optional(),
    quote_tweet_id: z.union([
        z.number().int(),
        z.null()
    ]).optional()
});

/**
 * InteractWithTweetResponseContent
 */
export const zInteractWithTweetResponseContent: z.AnyZodObject = z.object({
    interaction_result: zTweetInteractionResult
});

/**
 * SendMessageResponseContent
 */
export const zSendMessageResponseContent: z.AnyZodObject = z.object({
    message_info: zMessageInfo
});

/**
 * ReplyToMessageResponseContent
 */
export const zReplyToMessageResponseContent: z.AnyZodObject = z.object({
    message_info: zMessageInfo
});

/**
 * LeaveGroupResponseContent
 */
export const zLeaveGroupResponseContent: z.AnyZodObject = z.object({});

/**
 * ChannelInfo
 */
export const zChannelInfo: z.AnyZodObject = z.object({
    id: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    name: z.union([
        z.string(),
        z.null()
    ]).optional(),
    phone_number: z.union([
        z.string(),
        z.null()
    ]).optional(),
    title: z.union([
        z.string(),
        z.null()
    ]).optional(),
    type: z.union([
        zChatType,
        z.null()
    ]).optional(),
    description: z.union([
        z.string(),
        z.null()
    ]).optional(),
    read_inbox_max_id: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    read_outbox_max_id: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    unread_count: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    unread_mentions_count: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    unread_reactions_count: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    subscribers: z.union([
        z.number().int(),
        z.null()
    ]).optional()
});

/**
 * GroupInfo
 */
export const zGroupInfo: z.AnyZodObject = z.object({
    id: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    name: z.union([
        z.string(),
        z.null()
    ]).optional(),
    phone_number: z.union([
        z.string(),
        z.null()
    ]).optional(),
    title: z.union([
        z.string(),
        z.null()
    ]).optional(),
    type: z.union([
        zChatType,
        z.null()
    ]).optional(),
    description: z.union([
        z.string(),
        z.null()
    ]).optional(),
    read_inbox_max_id: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    read_outbox_max_id: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    unread_count: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    unread_mentions_count: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    unread_reactions_count: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    members: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    online: z.union([
        z.number().int(),
        z.null()
    ]).optional()
});

/**
 * JoinGroupResponseContent
 */
export const zJoinGroupResponseContent: z.AnyZodObject = z.object({
    chat_info: z.union([
        zChannelInfo,
        zGroupInfo,
        z.null()
    ]),
    discussion_group_chat_info: z.union([
        zChannelInfo,
        zGroupInfo,
        z.null()
    ])
});

/**
 * ForwardMessageResponseContent
 */
export const zForwardMessageResponseContent: z.AnyZodObject = z.object({
    message_info: zMessageInfo
});

/**
 * BehaviouralResponseContent
 */
export const zBehaviouralResponseContent: z.AnyZodObject = z.object({
    current_context: z.unknown().optional(),
    chats: z.union([
        z.array(z.union([
            zGroupInfo,
            zChannelInfo
        ])),
        z.null()
    ]).optional(),
    personal_details_synced: z.union([
        z.boolean(),
        z.null()
    ]).optional(),
    auto_download_media_disabled: z.union([
        z.boolean(),
        z.null()
    ]).optional(),
    all_active_sessions_deleted: z.union([
        z.boolean(),
        z.null()
    ]).optional(),
    unread_messages: z.union([
        z.array(zChatInfo),
        z.null()
    ]).optional()
});

/**
 * SendBulkMessagesResponseContent
 */
export const zSendBulkMessagesResponseContent: z.AnyZodObject = z.object({
    message_infos: z.array(zMessageInfo)
});

/**
 * ReadMessagesResponseContent
 */
export const zReadMessagesResponseContent: z.AnyZodObject = z.object({
    messages_read: z.number().int()
});

/**
 * UserInfo
 */
export const zUserInfo: z.AnyZodObject = z.object({
    id: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    name: z.union([
        z.string(),
        z.null()
    ]).optional(),
    phone_number: z.union([
        z.string(),
        z.null()
    ]).optional(),
    title: z.union([
        z.string(),
        z.null()
    ]).optional(),
    type: z.union([
        zChatType,
        z.null()
    ]).optional(),
    description: z.union([
        z.string(),
        z.null()
    ]).optional(),
    read_inbox_max_id: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    read_outbox_max_id: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    unread_count: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    unread_mentions_count: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    unread_reactions_count: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    subtitle: z.union([
        z.string(),
        z.null()
    ]).optional()
});

/**
 * ResolvePhoneResponseContent
 */
export const zResolvePhoneResponseContent: z.AnyZodObject = z.object({
    user_info: z.union([
        zUserInfo,
        z.null()
    ]).optional(),
    error: z.union([
        z.string(),
        z.null()
    ]).optional()
});

/**
 * CloseBrowserResponseContent
 */
export const zCloseBrowserResponseContent: z.AnyZodObject = z.object({
    closed: z.union([
        z.boolean(),
        z.null()
    ]).optional()
});

/**
 * ActionCreate
 */
export const zActionCreate: z.AnyZodObject = z.object({
    avatar_id: z.string().uuid().optional(),
    start_time: z.string().datetime(),
    end_time: z.union([
        z.string().datetime(),
        z.null()
    ]).optional(),
    action_type: zType,
    platform: zPlatform,
    request_payload: z.union([
        zScrollFeedArgs,
        zSendMessageArgs,
        zSendBulkMessagesArgs,
        zJoinGroupArgs,
        zLeaveGroupArgs,
        zReplyToMessageArgs,
        zForwardMessageArgs,
        zBehaviouralArgs,
        zReadMessagesArgs,
        zResolvePhoneArgs,
        zInteractWithTweetArgs,
        zInteractWithTweetByTweetIdArgs,
        zCloseBrowserArgs,
        z.null()
    ]),
    status: zActionStatus,
    response_content: z.union([
        zScrollFeedResponseContent,
        zInteractWithTweetResponseContent,
        zSendMessageResponseContent,
        zReplyToMessageResponseContent,
        zLeaveGroupResponseContent,
        zJoinGroupResponseContent,
        zForwardMessageResponseContent,
        zBehaviouralResponseContent,
        zSendBulkMessagesResponseContent,
        zReadMessagesResponseContent,
        zResolvePhoneResponseContent,
        zCloseBrowserResponseContent,
        z.null()
    ])
});

/**
 * ActionPlatform
 */
export const zActionPlatform = z.enum([
    'x'
]);

/**
 * ActionResultStatusCode
 */
export const zActionResultStatusCode = z.enum([
    'success',
    'failed',
    'cancelled',
    'fail_fast',
    'running',
    'pending'
]);

/**
 * ActionResultStatus
 */
export const zActionResultStatus = z.object({
    status_code: zActionResultStatusCode,
    error: z.union([
        z.string(),
        z.null()
    ]).optional()
});

/**
 * MimeType
 */
export const zMimeType = z.enum([
    'image/jpeg',
    'image/jpg',
    'image/png',
    'image/gif',
    'image/webp',
    'video/mp4',
    'video/webm'
]);

/**
 * AttachmentData
 */
export const zAttachmentData = z.object({
    url: z.string(),
    s3_uri: z.union([
        z.string(),
        z.null()
    ]).optional(),
    name: z.union([
        z.string(),
        z.null()
    ]).optional(),
    mime_type: zMimeType
});

/**
 * MetricsData
 */
export const zMetricsData: z.AnyZodObject = z.object({
    likes: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    retweets: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    bookmarks: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    replies: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    quotes: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    impressions: z.union([
        z.number().int(),
        z.null()
    ]).optional()
});

/**
 * TweetData
 */
export const zTweetData: z.AnyZodObject = z.object({
    tweet_id: z.number().int(),
    author_id: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    author_name: z.union([
        z.string(),
        z.null()
    ]).optional(),
    author_username: z.union([
        z.string(),
        z.null()
    ]).optional(),
    creation_date: z.union([
        z.string(),
        z.null()
    ]).optional(),
    text: z.string(),
    media: z.array(zAttachmentData).optional().default([]),
    media_description: z.union([
        z.string(),
        z.null()
    ]).optional(),
    inner_tweet: z.union([
        z.lazy(() => {
            return zTweetData;
        }),
        z.null()
    ]).optional(),
    metrics: z.union([
        zMetricsData,
        z.null()
    ]).optional(),
    summary: z.union([
        z.string(),
        z.null()
    ]).optional()
});

/**
 * ScrollFeedActionData
 */
export const zScrollFeedActionData: z.AnyZodObject = z.object({
    url: z.union([
        z.string(),
        z.null()
    ]).optional(),
    tweets: z.array(zTweetData)
});

/**
 * LikeTweetActionData
 */
export const zLikeTweetActionData: z.AnyZodObject = z.object({
    tweet: z.union([
        zTweetData,
        z.null()
    ]).optional()
});

/**
 * RetweetActionData
 */
export const zRetweetActionData: z.AnyZodObject = z.object({
    tweet: z.union([
        zTweetData,
        z.null()
    ]).optional()
});

/**
 * BookmarkActionData
 */
export const zBookmarkActionData: z.AnyZodObject = z.object({
    tweet: z.union([
        zTweetData,
        z.null()
    ]).optional()
});

/**
 * ReplyActionData
 */
export const zReplyActionData: z.AnyZodObject = z.object({
    tweet: z.union([
        zTweetData,
        z.null()
    ]).optional(),
    reply_content: z.union([
        z.string(),
        z.null()
    ]).optional(),
    reply_id: z.union([
        z.number().int(),
        z.null()
    ]).optional()
});

/**
 * QuoteActionData
 */
export const zQuoteActionData: z.AnyZodObject = z.object({
    tweet: z.union([
        zTweetData,
        z.null()
    ]).optional(),
    quote_content: z.union([
        z.string(),
        z.null()
    ]).optional(),
    quote_id: z.union([
        z.number().int(),
        z.null()
    ]).optional()
});

/**
 * ActionUpdate
 */
export const zActionUpdate: z.AnyZodObject = z.object({
    data: z.union([
        zScrollFeedActionData,
        zLikeTweetActionData,
        zRetweetActionData,
        zBookmarkActionData,
        zReplyActionData,
        zQuoteActionData,
        z.null()
    ]).optional()
});

/**
 * ActivityTimeParameters
 */
export const zActivityTimeParameters = z.object({
    A1: z.number().gte(0).lte(1).optional(),
    mu1: z.number().gte(0).lte(12).optional(),
    sigma1: z.number().gte(1).lte(3).optional(),
    A2: z.number().gte(0).lte(1).optional(),
    mu2: z.number().gte(12).lte(24).optional(),
    sigma2: z.number().gte(1).lte(4).optional(),
    baseline: z.number().gte(0).lte(1).optional(),
    target_actions_per_day: z.number().int().gte(0).lte(100).optional()
});

/**
 * Address
 */
export const zAddress = z.object({
    street: z.union([
        z.string(),
        z.null()
    ]).optional(),
    city: z.string(),
    state: z.union([
        z.string(),
        z.null()
    ]).optional(),
    country: z.string(),
    timezone: z.string(),
    postal_code: z.union([
        z.string(),
        z.null()
    ]).optional(),
    iso_3166_1_alpha_2_code: z.string(),
    iso_3166_2_subdivision_code: z.string()
});

/**
 * AddressUpdate
 */
export const zAddressUpdate = z.object({
    street: z.union([
        z.string(),
        z.null()
    ]).optional(),
    city: z.union([
        z.string(),
        z.null()
    ]).optional(),
    state: z.union([
        z.string(),
        z.null()
    ]).optional(),
    country: z.union([
        z.string(),
        z.null()
    ]).optional(),
    timezone: z.union([
        z.string(),
        z.null()
    ]).optional(),
    postal_code: z.union([
        z.string(),
        z.null()
    ]).optional(),
    iso_3166_1_alpha_2_code: z.union([
        z.string(),
        z.null()
    ]).optional(),
    iso_3166_2_subdivision_code: z.union([
        z.string(),
        z.null()
    ]).optional()
});

/**
 * Email
 */
export const zEmail = z.object({
    username: z.string(),
    password: z.string()
});

/**
 * SocialPlatform
 */
export const zSocialPlatform = z.enum([
    'x',
    'telegram'
]);

/**
 * SocialMediaAccountCreate
 */
export const zSocialMediaAccountCreate = z.object({
    platform: zSocialPlatform,
    username: z.string(),
    password: z.string(),
    active: z.boolean().optional().default(false),
    profile_image_url: z.union([
        z.string(),
        z.null()
    ]).optional(),
    subject_image_url: z.union([
        z.string(),
        z.null()
    ]).optional()
});

/**
 * AvatarCreate
 */
export const zAvatarCreate = z.object({
    first_name: z.string(),
    last_name: z.string(),
    gender: z.string(),
    language: z.string(),
    birth_date: z.string().date(),
    address: zAddress,
    bio: z.string(),
    interests: z.array(z.string()).optional(),
    habits: z.array(z.string()).optional(),
    phone_number: z.string(),
    image_url: z.string().optional().default(''),
    emails: z.array(zEmail).optional(),
    social_media_accounts: z.array(zSocialMediaAccountCreate).optional()
});

/**
 * AvatarStateEnum
 */
export const zAvatarStateEnum = z.enum([
    'available',
    'active',
    'invalid'
]);

/**
 * AvatarState
 */
export const zAvatarState = z.object({
    id: z.string().uuid().optional(),
    created_at: z.string().datetime().optional(),
    updated_at: z.string().datetime().optional(),
    state: zAvatarStateEnum.optional(),
    avatar_id: z.string().uuid()
});

/**
 * SocialMediaAccountRead
 */
export const zSocialMediaAccountRead = z.object({
    platform: zSocialPlatform,
    username: z.string(),
    password: z.string(),
    active: z.boolean().optional().default(false),
    profile_image_url: z.union([
        z.string(),
        z.null()
    ]).optional(),
    subject_image_url: z.union([
        z.string(),
        z.null()
    ]).optional()
});

/**
 * Status
 */
export const zStatus = z.enum([
    'active',
    'expired',
    'invalid'
]);

/**
 * Version
 */
export const zVersion = z.enum([
    'IPV4',
    'IPV6'
]);

/**
 * ProxyType
 */
export const zProxyType = z.enum([
    'HTTP',
    'HTTPS',
    'SOCKS5'
]);

/**
 * ProxyRead
 */
export const zProxyRead = z.object({
    id: z.string().uuid(),
    created_at: z.string().datetime(),
    updated_at: z.string().datetime(),
    name: z.string(),
    status: z.union([
        zStatus,
        z.null()
    ]).optional(),
    version: zVersion,
    proxy_type: zProxyType,
    port: z.number().int(),
    ip_address: z.union([
        z.string(),
        z.null()
    ]).optional(),
    fqdn: z.union([
        z.string(),
        z.null()
    ]).optional(),
    username: z.string(),
    password: z.string(),
    continent_code: z.union([
        z.string(),
        z.null()
    ]).optional(),
    iso_3166_1_alpha_2_code: z.union([
        z.string(),
        z.null()
    ]).optional(),
    iso_3166_2_subdivision_code: z.union([
        z.string(),
        z.null()
    ]).optional(),
    city: z.union([
        z.string(),
        z.null()
    ]).optional(),
    expired_date: z.string().date(),
    batch_id: z.string().uuid(),
    last_pinged: z.union([
        z.string().datetime(),
        z.null()
    ]).optional(),
    extra_data: z.union([
        z.object({}),
        z.null()
    ]).optional(),
    proxy_full_url: z.union([
        z.string(),
        z.null()
    ]).optional()
});

/**
 * AvatarRead
 */
export const zAvatarRead = z.object({
    activity_time_parameters: zActivityTimeParameters.optional(),
    force_awake: z.boolean().optional().default(false),
    force_shutdown: z.boolean().optional().default(false),
    strategy: z.union([
        z.string(),
        z.null()
    ]).optional(),
    strategy_expiration: z.union([
        z.string().datetime(),
        z.null()
    ]).optional(),
    first_name: z.string(),
    last_name: z.string(),
    gender: z.string(),
    language: z.string(),
    birth_date: z.string().date(),
    address: zAddress,
    bio: z.string(),
    interests: z.array(z.string()).optional(),
    habits: z.array(z.string()).optional(),
    phone_number: z.string(),
    image_url: z.string().optional().default(''),
    emails: z.array(zEmail).optional(),
    id: z.string().uuid(),
    avatar_state: zAvatarState,
    social_media_accounts: z.array(zSocialMediaAccountRead),
    proxy: z.union([
        zProxyRead,
        z.null()
    ]).optional()
});

/**
 * AvatarUpdate
 */
export const zAvatarUpdate = z.object({
    first_name: z.union([
        z.string(),
        z.null()
    ]).optional(),
    last_name: z.union([
        z.string(),
        z.null()
    ]).optional(),
    phone_number: z.union([
        z.string(),
        z.null()
    ]).optional(),
    image_url: z.union([
        z.string(),
        z.null()
    ]).optional(),
    birth_date: z.union([
        z.string().date(),
        z.null()
    ]).optional(),
    gender: z.union([
        z.string(),
        z.null()
    ]).optional(),
    language: z.union([
        z.string(),
        z.null()
    ]).optional(),
    address: z.union([
        zAddressUpdate,
        z.null()
    ]).optional(),
    emails: z.union([
        z.array(zEmail),
        z.null()
    ]).optional(),
    bio: z.union([
        z.string(),
        z.null()
    ]).optional(),
    interests: z.union([
        z.array(z.string()),
        z.null()
    ]).optional(),
    habits: z.union([
        z.array(z.string()),
        z.null()
    ]).optional(),
    strategy: z.union([
        z.string(),
        z.null()
    ]).optional(),
    strategy_expiration: z.union([
        z.string().datetime(),
        z.null()
    ]).optional()
});

/**
 * Body_saveProfileImage
 */
export const zBodySaveProfileImage = z.object({
    image_b64: z.string()
});

/**
 * BookmarkActionRead
 */
export const zBookmarkActionRead = z.object({
    id: z.string().uuid(),
    avatar_id: z.string().uuid(),
    type: z.literal('bookmark'),
    platform: z.union([
        zActionPlatform,
        z.null()
    ]).optional(),
    status: zActionResultStatus,
    created_at: z.string().datetime(),
    data: zBookmarkActionData
});

/**
 * GenerateProfileImageResponse
 */
export const zGenerateProfileImageResponse = z.object({
    image_b64: z.string()
});

/**
 * LikeActionRead
 */
export const zLikeActionRead = z.object({
    id: z.string().uuid(),
    avatar_id: z.string().uuid(),
    type: z.literal('like'),
    platform: z.union([
        zActionPlatform,
        z.null()
    ]).optional(),
    status: zActionResultStatus,
    created_at: z.string().datetime(),
    data: zLikeTweetActionData
});

/**
 * QuoteActionRead
 */
export const zQuoteActionRead = z.object({
    id: z.string().uuid(),
    avatar_id: z.string().uuid(),
    type: z.literal('quote'),
    platform: z.union([
        zActionPlatform,
        z.null()
    ]).optional(),
    status: zActionResultStatus,
    created_at: z.string().datetime(),
    data: zQuoteActionData
});

/**
 * ReplyActionRead
 */
export const zReplyActionRead = z.object({
    id: z.string().uuid(),
    avatar_id: z.string().uuid(),
    type: z.literal('reply'),
    platform: z.union([
        zActionPlatform,
        z.null()
    ]).optional(),
    status: zActionResultStatus,
    created_at: z.string().datetime(),
    data: zReplyActionData
});

/**
 * RetweetActionRead
 */
export const zRetweetActionRead = z.object({
    id: z.string().uuid(),
    avatar_id: z.string().uuid(),
    type: z.literal('retweet'),
    platform: z.union([
        zActionPlatform,
        z.null()
    ]).optional(),
    status: zActionResultStatus,
    created_at: z.string().datetime(),
    data: zRetweetActionData
});

/**
 * ScrollActionRead
 */
export const zScrollActionRead = z.object({
    id: z.string().uuid(),
    avatar_id: z.string().uuid(),
    type: z.literal('scroll'),
    platform: z.union([
        zActionPlatform,
        z.null()
    ]).optional(),
    status: zActionResultStatus,
    created_at: z.string().datetime(),
    data: zScrollFeedActionData
});

/**
 * StateInterval
 */
export const zStateInterval = z.object({
    state: zAvatarStateEnum,
    started_at: z.string().datetime(),
    ended_at: z.union([
        z.string().datetime(),
        z.null()
    ]).optional()
});

export const zGetAvatarsData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        attach_proxy: z.boolean().optional().default(false),
        limit: z.number().int().optional().default(100),
        offset: z.number().int().optional().default(0)
    }).optional()
});

/**
 * Response Getavatars
 * Successful Response
 */
export const zGetAvatarsResponse = z.array(zAvatarRead);

export const zCreateAvatarData = z.object({
    body: zAvatarCreate,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zCreateAvatarResponse = zAvatarRead;

export const zGenerateAvatarData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        payload: z.string()
    })
});

/**
 * Successful Response
 */
export const zGenerateAvatarResponse = zAvatarCreate;

export const zAvailableAvatarsData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        interval: z.number().int(),
        limit: z.number().int().optional().default(100),
        offset: z.number().int().optional().default(0)
    })
});

/**
 * Response Availableavatars
 * Successful Response
 */
export const zAvailableAvatarsResponse = z.array(z.string().uuid());

export const zForcedStoppedAvatarsData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Response Forcedstoppedavatars
 * Successful Response
 */
export const zForcedStoppedAvatarsResponse = z.array(z.string().uuid());

export const zDeleteAvatarData = z.object({
    body: z.never().optional(),
    path: z.object({
        avatar_id: z.string().uuid()
    }),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zDeleteAvatarResponse = z.void();

export const zGetAvatarData = z.object({
    body: z.never().optional(),
    path: z.object({
        avatar_id: z.string().uuid()
    }),
    query: z.object({
        attach_proxy: z.boolean().optional().default(false)
    }).optional()
});

/**
 * Successful Response
 */
export const zGetAvatarResponse = zAvatarRead;

export const zUpdateAvatarData = z.object({
    body: zAvatarUpdate,
    path: z.object({
        avatar_id: z.string().uuid()
    }),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zUpdateAvatarResponse = zAvatarRead;

export const zWakingUpProbData = z.object({
    body: z.never().optional(),
    path: z.object({
        avatar_id: z.string().uuid()
    }),
    query: z.object({
        interval_in_seconds: z.number().int()
    })
});

/**
 * Response Wakingupprob
 * Successful Response
 */
export const zWakingUpProbResponse = z.number();

export const zUpdateAvatarStateData = z.object({
    body: z.never().optional(),
    path: z.object({
        avatar_id: z.string().uuid(),
        state: zAvatarStateEnum
    }),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zUpdateAvatarStateResponse = zAvatarRead;

export const zGetAvatarStateData = z.object({
    body: z.never().optional(),
    path: z.object({
        avatar_id: z.string().uuid()
    }),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zGetAvatarStateResponse = zAvatarStateEnum;

export const zDeleteAvatarStateData = z.object({
    body: z.never().optional(),
    path: z.object({
        state_id: z.string().uuid()
    }),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zDeleteAvatarStateResponse = z.void();

export const zGetAvatarStateHistoryData = z.object({
    body: z.never().optional(),
    path: z.object({
        avatar_id: z.string().uuid()
    }),
    query: z.object({
        hours_ago: z.number().int().optional().default(24)
    }).optional()
});

/**
 * Response Getavatarstatehistory
 * Successful Response
 */
export const zGetAvatarStateHistoryResponse = z.array(zStateInterval);

export const zForceShutdownAvatarData = z.object({
    body: z.never().optional(),
    path: z.object({
        avatar_id: z.string().uuid()
    }),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zForceShutdownAvatarResponse = z.void();

export const zForceAwakeAvatarData = z.object({
    body: z.never().optional(),
    path: z.object({
        avatar_id: z.string().uuid()
    }),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zForceAwakeAvatarResponse = z.void();

export const zGenerateProfileImageData = z.object({
    body: z.never().optional(),
    path: z.object({
        avatar_id: z.string().uuid()
    }),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zGenerateProfileImageResponse2 = zGenerateProfileImageResponse;

export const zSaveProfileImageData = z.object({
    body: zBodySaveProfileImage,
    path: z.object({
        avatar_id: z.string().uuid()
    }),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zSaveProfileImageResponse = zAvatarRead;

export const zGetActiveAvatarsCountByPlatformData = z.object({
    body: z.never().optional(),
    path: z.object({
        platform: zSocialPlatform
    }),
    query: z.never().optional()
});

/**
 * Response Getactiveavatarscountbyplatform
 * Successful Response
 */
export const zGetActiveAvatarsCountByPlatformResponse = z.number().int();

export const zCreateActionData = z.object({
    body: zActionCreate,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Response Createaction
 * Successful Response
 */
export const zCreateActionResponse = z.array(z.union([
    zScrollActionRead,
    zLikeActionRead,
    zRetweetActionRead,
    zBookmarkActionRead,
    zReplyActionRead,
    zQuoteActionRead
]));

export const zGetActionData = z.object({
    body: z.never().optional(),
    path: z.object({
        action_id: z.string().uuid()
    }),
    query: z.never().optional()
});

/**
 * Response Getaction
 * Successful Response
 */
export const zGetActionResponse = z.union([
    zScrollActionRead,
    zLikeActionRead,
    zRetweetActionRead,
    zBookmarkActionRead,
    zReplyActionRead,
    zQuoteActionRead
]);

export const zUpdateActionData = z.object({
    body: zActionUpdate,
    path: z.object({
        action_id: z.string().uuid()
    }),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zUpdateActionResponse = z.void();

export const zGetAvatarInteractionsData = z.object({
    body: z.never().optional(),
    path: z.object({
        avatar_id: z.string().uuid()
    }),
    query: z.object({
        success_only: z.boolean().optional().default(false),
        limit: z.number().int().gte(1).lte(1000).optional().default(100),
        offset: z.number().int().gte(0).optional().default(0)
    }).optional()
});

/**
 * Response Getavatarinteractions
 * Successful Response
 */
export const zGetAvatarInteractionsResponse = z.array(z.union([
    zLikeActionRead,
    zRetweetActionRead,
    zBookmarkActionRead,
    zReplyActionRead,
    zQuoteActionRead
]));

export const zGetAvatarInteractionsDescriptionsData = z.object({
    body: z.never().optional(),
    path: z.object({
        avatar_id: z.string().uuid()
    }),
    query: z.object({
        limit: z.number().int().gte(1).lte(1000).optional().default(100),
        offset: z.number().int().gte(0).optional().default(0)
    }).optional()
});

/**
 * Response Getavatarinteractionsdescriptions
 * Successful Response
 */
export const zGetAvatarInteractionsDescriptionsResponse = z.array(z.string());

export const zGetAvatarRepliesData = z.object({
    body: z.never().optional(),
    path: z.object({
        avatar_id: z.string().uuid()
    }),
    query: z.object({
        limit: z.number().int().optional().default(10)
    }).optional()
});

/**
 * Response Getavatarreplies
 * Successful Response
 */
export const zGetAvatarRepliesResponse = z.array(z.string());

export const zBoomBoomGetData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});